/**
 ***********************************************************************************************************************
 * @file        capi.hpp
 * @author      ${PROJECT_AUTHOR} (${PROJECT_CONTACT})
 * @date        ${PROJECT_BUILD_TIMESTAMP_UTC}
 * @version     ${PROJECT_VERSION}
 * @copyright   ${PROJECT_COPYRIGHT}
 ***********************************************************************************************************************
 */

#ifndef LUTILS_CCAPI_HPP
#define LUTILS_CCAPI_HPP

#include "priv/runtime.hpp"
#if defined(CAPICPP_CLIENT)
#include "priv/client.hpp"
#endif
#if defined(CAPICPP_SERVER)
#include "priv/server.hpp"
#endif

/**
 * @rst
 * The *capi* component, short for Common API C++, encapsulates the autogenerated code of the Common API C++ framework
 * generators from the relevant Franca IDL and deployment files and links the shared libraries generated from these to
 * the client and server executable targets of the application.
 *
 * Tooling, Runtimes and Libraries
 * -------------------------------
 *
 * The development container already has the Common API C++ generators, runtimes, libraries and dependencies available,
 * they are located in the *usr/local/capicpp* folder, as shown in the folder structure below. To understand the
 * full setup it is recommended to look at the *.devcontainer/DockerFile* file.
 *
 * .. code-block::
 *
 *     /usr/local/capicpp
 *     ├── core-runtime
 *     ├── core-tools
 *     ├── dbus-patched
 *     ├── dbus-runtime
 *     ├── dbus-tools
 *     ├── someip-runtime
 *     ├── someip-tools
 *     └── vsomeip
 *
 * The **core-runtime**, **dbus-runtime** and **someip-runtime** subfolders contain the Common API C++ core, D-Bus
 * and SOME/IP runtimes and their shared libraries for linking.
 *
 * The **core-tools**, **dbus-tools** and **someip-tools** subfolders contain the Common API C++ core, D-Bus
 * and SOME/IP generators to generate code from the ``.fidl`` and ``.fdepl`` files.
 *
 * The **dbus-patched** subfolder contains the compiled D-Bus library with the necessary patches from
 * Common API C++ already applied, this one is only used for linking with shared libraries in **dbus-runtime**.
 * The **vsomeip** folder contains the *vsomeip* shared libraries for the SOME/IP runtime binding.
 *
 * For convenience and as shown in the snippet below, the generator tools are also available in the ``PATH``
 * environment variable. There are also other environments variables for relevant installation directories.
 *
 * .. code-block:: powershell
 *
 *     PS > commonapi-core-generator --version
 *     Version:      3.2.15
 *     Build id:     20240402
 *     Architecture: 64 Bit
 *
 *     PS > commonapi-dbus-generator --version
 *     Version:      3.2.15
 *     Build id:     20240402
 *     Architecture: 64 Bit
 *
 *     PS > commonapi-someip-generator --version
 *     Version:      3.2.15
 *     Build id:     20240402
 *     Architecture: 64 Bit
 *
 *     PS > $ENV:CAPICPP_CORE_TOOLS_DIR
 *     /usr/local/capicpp/core-tools
 *
 *     PS > $ENV:CAPICPP_DBUS_TOOLS_DIR
 *     /usr/local/capicpp/dbus-tools
 *
 *     PS > $ENV:CAPICPP_SOMEIP_TOOLS_DIR
 *     /usr/local/capicpp/someip-tools
 *
 *     PS > $ENV:CAPICPP_CORE_RUNTIME_DIR
 *     /usr/local/capicpp/core-runtime
 *
 *     PS > $ENV:CAPICPP_DBUS_RUNTIME_DIR
 *     /usr/local/capicpp/dbus-runtime
 *
 *     PS > $ENV:CAPICPP_SOMEIP_RUNTIME_DIR
 *     /usr/local/capicpp/someip-runtime
 *
 *     PS > $ENV:CAPICPP_DBUS_DIR
 *     /usr/local/capicpp/dbus-patched
 *
 *     PS > $ENV:CAPICPP_VSOMEIP_DIR
 *     /usr/local/capicpp/vsomeip
 *
 * Generation of Source Code
 * -------------------------
 *
 * The folder *src/third_party/capi_gen* in the repository contains all the input Franca ``.fidl`` and ``.fdepl`` files
 * needed by the Common API C++ core, D-Bus and SOME/IP generators to generate source code from in the respective
 * *gen* folders. The configuration files are also kept in this folder. The detailed folder structure is shown below.
 *
 * .. code-block::
 *
 *     src/third_party/capi_gen
 *     ├── dbus
 *     │   ├── commonapi-dbus.ini
 *     │   ├── commonapi.ini
 *     │   └── gen
 *     │       ├── common
 *     │       ├── proxy
 *     │       └── stub
 *     ├── fidl
 *     │   ├── app.dbus.fdepl
 *     │   ├── app.fidl
 *     │   ├── app.someip.fdepl
 *     │   └── gen
 *     │       ├── common
 *     │       ├── proxy
 *     │       ├── skel
 *     │       └── stub
 *     └── someip
 *         ├── commonapi-someip.ini
 *         ├── commonapi.ini
 *         ├── gen
 *         │   ├── common
 *         │   ├── proxy
 *         │   └── stub
 *         └── vsomeip.json
 *
 * In the **fidl** subfolder, the files *app.fidl*, *app.dbus.fdepl* and *app.someip.fdepl* are the Franca language
 * files with the interface definition and deployment details for D-Bus and SOME/IP runtime bindings. The *gen*
 * folder contains the source code generated by the Common API C++ core generator, ``commonapi-core-generator``.
 *
 * In the **dbus** subfolder, the files *commonapi.ini* and *commonapi-dbus.ini* folder are the configuration files
 * suitable for the D-Bus runtime binding. The *gen* folder contains the source code generated by the Common API C++
 * D-Bus generator, ``commonapi-dbus-generator``.
 *
 * In the **someip** subfolder, the files *commonapi.ini*, *commonapi-someip.ini* and *vsomeip.json* folder are the
 * configuration files suitable for the SOME/IP runtime binding and vsomeip library. The *gen* folder contains the
 * source code generated by the Common API C++ SOME/IP generator, ``commonapi-someip-generator``.
 *
 * The generation of code can be done manually, or simply by executing the following script, which already takes
 * care of handling the directories and doing error checking.
 *
 * .. code-block:: powershell
 *
 *     ./manage.ps1 commonapi-gen
 *
 * @endrst
 */
namespace Utils::Capi
{

/**
 * @brief Internal implementation details.
 * @private
 */
namespace Priv
{ }

}

#endif /* LUTILS_CCAPI_HPP */

/******************************************************************************************************END OF FILE*****/
