# syntax=docker/dockerfile:1
# escape=\

# Use latest Debian available with PowerShell.
FROM mcr.microsoft.com/powershell:7.3-debian-bookworm

# Ensure working from a known working directory.
WORKDIR "/"
# Ensure the active shell is PowerShell.
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Update package sources, upgrade current installed packages and install new packages. For details refer to:
#   - https://packages.debian.org/index
#   - https://manpages.debian.org/stretch/apt/apt-get.8.en.html
#   - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ (apt-get)
#   - https://askubuntu.com/questions/875213/apt-get-to-retry-downloading (apt-get retries)
# It is possible that the Dockerfile breaks over time at this point as packages might be deprecated and not exist
# anymore when updates or upgrades are released, in this scenario, the package versions will need to be updated.
# 
# For details about the dependencies related to COVESA / GENIVI Common API C++ Generators, refer to:
#   - https://unix.stackexchange.com/a/749907
#   - https://stackoverflow.com/a/19654699
RUN 'Acquire::Retries "6";' > /etc/apt/apt.conf.d/80-retries;                                                          \
    Invoke-WebRequest "http://www.mirbsd.org/~tg/Debs/sources.txt/wtf-bookworm.sources" -OutFile "./out.sources";      \
    Move-Item -Path "./out.sources" -Destination "/etc/apt/sources.list.d/wtf-bookworm.sources" -Force;                \
    apt-get --assume-yes update;                                                                                       \
    apt-get --assume-yes upgrade;                                                                                      \
    apt-get --assume-yes --show-progress install                                                                       \
    ## C/C++ / Debuggers / Build Packages ##############################################################################
    gcc=4:12.2.0-3                                                                                                     \
    libc6-dev=2.36-9+deb12u9                                                                                           \
    gdb-multiarch=13.1-3                                                                                               \
    make=4.3-4.1                                                                                                       \
    ninja-build=1.11.1-2~deb12u1                                                                                       \
    cmake=3.25.1-1                                                                                                     \
                                                                                                                       \
    ## C/C++ Linters / Formatters / Documentation ######################################################################
    clang-format-15=1:15.0.6-4+b1                                                                                      \
    clang-tidy-15=1:15.0.6-4+b1                                                                                        \
    clangd-15=1:15.0.6-4+b1                                                                                            \
    cppcheck=2.10-2                                                                                                    \
    doxygen=1.9.4-4                                                                                                    \
    lcov=1.16-1                                                                                                        \
    graphviz=2.42.2-7+deb12u1                                                                                          \
    python3=3.11.2-1+b1                                                                                                \
    python-is-python3=3.11.2-1+deb12u1                                                                                 \
    python3-pip=23.0.1+dfsg-1                                                                                          \
    python3-venv=3.11.2-1+b1                                                                                           \
                                                                                                                       \
    ## COVESA / GENIVI Common API C++ Generators #######################################################################
    maven=3.8.7-1                                                                                                      \
    openjdk-8-jdk-headless                                                                                             \
    openjdk-8-jre-headless                                                                                             \
                                                                                                                       \
    ## COVESA / GENIVI Common API C++ Runtimes and Libraries ###########################################################
    patchelf                                                                                                           \
    pkg-config                                                                                                         \
    iproute2                                                                                                           \
    libdlt2=2.18.8-6                                                                                                   \
    libdlt-dev=2.18.8-6                                                                                                \
    libdbus-1-dev=1.14.10-1~deb12u1                                                                                    \
    libboost1.81-dev=1.81.0-5+deb12u1                                                                                  \
    libboost-system1.81-dev=1.81.0-5+deb12u1                                                                           \
    libboost-thread1.81-dev=1.81.0-5+deb12u1                                                                           \
    libboost-fileSystem1.81-dev=1.81.0-5+deb12u1                                                                       \
    libsystemd-dev=252.31-1~deb12u1                                                                                    \
                                                                                                                       \
    ## Other ###########################################################################################################
    git=1:2.39.5-0+deb12u1                                                                                             \
    wget                                                                                                               \
    xz-utils                                                                                                           \
    locales;                                                                                                           \
                                                                                                                       \
    apt-get --assume-yes clean;                                                                                        \
    apt-get --assume-yes autoremove;                                                                                   \
    Remove-Item "/etc/apt/sources.list.d/wtf-bookworm.sources";

# Create the JAVA_HOME environment variable, so that proper version is used system wide.
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

# Download the NET Runtime, necessary for the 'josetr.cmake-language-support-vscode' extension, for details refer to:
#   - https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian
RUN wget "https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb" -O "package.deb";               \
    dpkg --install "./package.deb";                                                                                    \
    apt-get --assume-yes update;                                                                                       \
    apt-get --assume-yes --show-progress install dotnet-runtime-7.0;                                                   \
    apt-get --assume-yes clean;                                                                                        \
    apt-get --assume-yes autoremove;                                                                                   \
    Remove-Item "./package.deb" -Force;

# Ensure locales are properly installed.
# See: https://stackoverflow.com/a/41648500
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Additional Git configurations, refer to:
#   - https://linuxhint.com/git-handle-symbolic-links/#3
#   - https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning
#   - https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key
# This forces the signing of all commits, user must provide 'user.name', 'user.email' and 'user.signingkey'.
RUN git config --global core.symlinks true;                                                                            \
    git config --global http.postBuffer 500M;                                                                          \
    git config --global http.maxRequestBuffer 100M;                                                                    \
    git config --global core.compression 0;                                                                            \
    git config --global gpg.format ssh;                                                                                \
    git config --global commit.gpgsign true;

## Python Virtual Environment ##########################################################################################
# Copy 'pyproject.toml' file and 'poetry.lock' file, if it exists, to the virtual environments directory.
COPY "../pyproject.toml" "/usr/venvs/pyproject.toml"
COPY "../poetry.[l]ock" "/usr/venvs/poetry.lock"

# Create the virtual environment, activate it and:
#   - Install poetry with pip and use it for package management.
#   - Install 'production' and 'development' dependencies with Poetry.
#   - Do not use caches to decrease size of the image.
RUN Push-Location "/usr/venvs";                                                                                        \
    python -m venv "development";                                                                                      \
    & "/usr/venvs/development/bin/Activate.ps1";                                                                       \
    pip install --no-cache-dir poetry==1.5.1;                                                                          \
    poetry install --only main,dev --no-cache --no-interaction;                                                        \
    deactivate;                                                                                                        \
    Pop-Location;

# Export the path where the Python virtual environment is located as an environment variable.
ENV VIRTUAL_ENV_PATH="/usr/venvs/development"

## CommonAPI C++ Tools #################################################################################################
# Build and install CommonAPI C++ Core, D-Bus and SOME/IP tools, for reference, refer to the following links:
#   - Core: https://github.com/COVESA/capicxx-core-tools/tree/3.2.15
#   - D-Bus: https://github.com/COVESA/capicxx-dbus-tools/tree/3.2.15
#   - SOME/IP: https://github.com/COVESA/capicxx-someip-tools/tree/3.2.15
RUN                                                                                                                    \
    ## Build CommonAPI C++ Core Tools ##################################################################################
    git clone --depth 1 -b "3.2.15" "https://github.com/COVESA/capicxx-core-tools.git" "/core-tools";                  \
    Push-Location "/core-tools";                                                                                       \
    mvn -f "./org.genivi.commonapi.core.releng/pom.xml"                                                                \
        -D "target.id=org.genivi.commonapi.core.target" clean verify;                                                  \
    Pop-Location;                                                                                                      \
    ## Build CommonAPI C++ D-Bus Tools #################################################################################
    git clone --depth 1 -b "3.2.15" "https://github.com/COVESA/capicxx-dbus-tools.git" "/dbus-tools";                  \
    Push-Location "/dbus-tools";                                                                                       \
    mvn -f "./org.genivi.commonapi.dbus.releng/pom.xml"                                                                \
        -D "COREPATH=/core-tools"                                                                                      \
        -D "target.id=org.genivi.commonapi.dbus.target" clean verify;                                                  \
    Pop-Location;                                                                                                      \
    ## Build CommonAPI C++ SOME/IP Tools ###############################################################################
    git clone --depth 1 -b "3.2.15" "https://github.com/COVESA/capicxx-someip-tools.git" "/someip-tools";              \
    Push-Location "/someip-tools";                                                                                     \
    mvn -f "./org.genivi.commonapi.someip.releng/pom.xml"                                                              \
        -D "COREPATH=/core-tools"                                                                                      \
        -D "target.id=org.genivi.commonapi.someip.target" clean verify;                                                \
    Pop-Location;                                                                                                      \
    ## Installation of all tools #######################################################################################
    Expand-Archive -Force                                                                                              \
        -Path "/core-tools/org.genivi.commonapi.core.cli.product/target/products/commonapi_core_generator.zip"         \
        -DestinationPath "/usr/local/capicpp/core-tools";                                                              \
    ln -sf '/usr/local/capicpp/core-tools/commonapi-core-generator-linux-x86_64'                                       \
           '/usr/bin/commonapi-core-generator';                                                                        \
    Expand-Archive -Force                                                                                              \
        -Path "/dbus-tools/org.genivi.commonapi.dbus.cli.product/target/products/commonapi_dbus_generator.zip"         \
        -DestinationPath "/usr/local/capicpp/dbus-tools";                                                              \
    ln -sf '/usr/local/capicpp/dbus-tools/commonapi-dbus-generator-linux-x86_64'                                       \
           '/usr/bin/commonapi-dbus-generator';                                                                        \
    Expand-Archive -Force                                                                                              \
        -Path "/someip-tools/org.genivi.commonapi.someip.cli.product/target/products/commonapi_someip_generator.zip"   \
        -DestinationPath "/usr/local/capicpp/someip-tools";                                                            \
    ln -sf '/usr/local/capicpp/someip-tools/commonapi-someip-generator-linux-x86_64'                                   \
           '/usr/bin/commonapi-someip-generator';                                                                      \
    ## Cleanup #########################################################################################################
    Remove-Item "/core-tools" -Force -Recurse;                                                                         \
    Remove-Item "/dbus-tools" -Force -Recurse;                                                                         \
    Remove-Item "/someip-tools" -Force -Recurse;                                                                       \
    Remove-Item "/root/.m2/repository" -Force -Recurse;
ENV CAPICPP_CORE_TOOLS_DIR="/usr/local/capicpp/core-tools"
ENV CAPICPP_DBUS_TOOLS_DIR="/usr/local/capicpp/dbus-tools"
ENV CAPICPP_SOMEIP_TOOLS_DIR="/usr/local/capicpp/someip-tools"

## CommonAPI C++ Runtimes ##############################################################################################
# Build and install CommonAPI C++ Core, D-Bus and SOME/IP runtimes, for reference, refer to the following links:
#   - Core: https://github.com/COVESA/capicxx-core-tools/tree/3.2.15
#   - D-Bus: https://github.com/COVESA/capicxx-dbus-tools/tree/3.2.15
#     - Patch ELF RPATH to link with patched D-Bus library: https://stackoverflow.com/a/54723461
#   - SOME/IP: https://github.com/COVESA/capicxx-someip-runtime/tree/3.2.4
#     - vsomeip: https://github.com/COVESA/vsomeip/tree/3.5.3
#   - Shared libraries configuration: https://stackoverflow.com/a/13428971
RUN                                                                                                                    \
    ## Build and install CommonAPI C++ Core Runtime ####################################################################
    git clone --depth 1 -b "3.2.4" "https://github.com/COVESA/capicxx-core-runtime.git" "/core-runtime";               \
    Push-Location "/core-runtime";                                                                                     \
    cmake --fresh -S "." -B "./.cmake_build"                                                                           \
        -DCMAKE_INSTALL_PREFIX:STRING="/usr/local/capicpp/core-runtime";                                               \
    cmake --build "./.cmake_build" --target all;                                                                       \
    cmake --build "./.cmake_build" --target install;                                                                   \
    Pop-Location;                                                                                                      \
    ## Build and install patched D-Bus Library and CommonAPI C++ D-Bus Runtime Library #################################
    git clone --depth 1 -b "3.2.3-r1" "https://github.com/COVESA/capicxx-dbus-runtime.git" "/dbus-runtime";            \
    wget "http://dbus.freedesktop.org/releases/dbus/dbus-1.13.6.tar.gz" -O "/dbus.tar.gz";                             \
    New-Item -Path "/dbus" -ItemType Directory -Force | Out-Null; tar -xzf "/dbus.tar.gz" -C "/dbus";                  \
    Push-Location "/dbus/dbus-1.13.6";                                                                                 \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-1-pc.patch";                                               \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-add-send-with-reply-set-notify.patch";                     \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-add-support-for-custom-marshalling.patch";                 \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-block-acquire-io-path-on-send.patch";                      \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-correct-dbus-connection-block-pending-call.patch";         \
    patch -Np1 -i "/dbus-runtime/src/dbus-patches/capi-dbus-send-with-reply-and-block-delete-reply-on-error.patch";    \
    cmake --fresh -S "./cmake" -B "./.cmake_build"                                                                     \
        -DCMAKE_INSTALL_PREFIX:STRING="/usr/local/capicpp/dbus-patched"                                                \
        -DDBUS_BUILD_TESTS:BOOL=OFF;                                                                                   \
    cmake --build "./.cmake_build" --target all;                                                                       \
    cmake --build "./.cmake_build" --target install;                                                                   \
    Pop-Location;                                                                                                      \
    Push-Location "/dbus-runtime";                                                                                     \
    cmake --fresh -S "." -B "./.cmake_build"                                                                           \
        -DCommonAPI_DIR:STRING="/usr/local/capicpp/core-runtime/lib/cmake/CommonAPI-3.2.4"                             \
        -DDBus1_DIR:STRING="/usr/local/capicpp/dbus-patched/lib/cmake/DBus1"                                           \
        -DUSE_INSTALLED_COMMONAPI:BOOL=OFF                                                                             \
        -DUSE_INSTALLED_DBUS:BOOL=OFF                                                                                  \
        -DCMAKE_INSTALL_PREFIX:STRING="/usr/local/capicpp/dbus-runtime";                                               \
    cmake --build "./.cmake_build" --target all;                                                                       \
    cmake --build "./.cmake_build" --target install;                                                                   \
    Pop-Location;                                                                                                      \
    ## Build and install vsomeip library and CommonAPI C++ SOME/IP Runtime #############################################
    git clone --depth 1 -b "3.5.3" "https://github.com/COVESA/vsomeip.git" "/vsomeip";                                 \
    Push-Location "/vsomeip";                                                                                          \
    cmake --fresh -S "." -B "./.cmake_build"                                                                           \
        -DCMAKE_INSTALL_PREFIX:STRING="/usr/local/capicpp/vsomeip";                                                    \
    cmake --build "./.cmake_build" --target all;                                                                       \
    cmake --build "./.cmake_build" --target install;                                                                   \
    Pop-Location;                                                                                                      \
    git clone --depth 1 -b "3.2.4" "https://github.com/COVESA/capicxx-someip-runtime.git" "/someip-runtime";           \
    Push-Location "/someip-runtime";                                                                                   \
    cmake --fresh -S "." -B "./.cmake_build"                                                                           \
        -DCommonAPI_DIR:STRING="/usr/local/capicpp/core-runtime/lib/cmake/CommonAPI-3.2.4"                             \
        -Dvsomeip3_DIR:STRING="/usr/local/capicpp/vsomeip/lib/cmake/vsomeip3"                                          \
        -DUSE_INSTALLED_COMMONAPI:BOOL=OFF                                                                             \
        -DCMAKE_INSTALL_PREFIX:STRING="/usr/local/capicpp/someip-runtime";                                             \
    cmake --build "./.cmake_build" --target all;                                                                       \
    cmake --build "./.cmake_build" --target install;                                                                   \
    Pop-Location;                                                                                                      \
    ## Set dynamic link paths and configuration ########################################################################
    $contents = "/usr/local/capicpp/core-runtime/lib" + "`n";                                                          \
    $contents += "/usr/local/capicpp/dbus-runtime/lib" + "`n";                                                         \
    $contents += "/usr/local/capicpp/vsomeip/lib" + "`n";                                                              \
    $contents += "/usr/local/capicpp/someip-runtime/lib" + "`n";                                                       \
    Set-Content -Path '/etc/ld.so.conf.d/capicpp.conf' -Force -Value "$($contents)" -Encoding utf8;                    \
    patchelf --set-rpath '$ORIGIN/../../dbus-patched/lib' '/usr/local/capicpp/dbus-runtime/lib/libCommonAPI-DBus.so';  \
    ldconfig;                                                                                                          \
    ## Cleanup #########################################################################################################
    Remove-Item "/core-runtime" -Force -Recurse;                                                                       \
    Remove-Item "/dbus-runtime" -Force -Recurse;                                                                       \
    Remove-Item "/dbus.tar.gz" -Force -Recurse;                                                                        \
    Remove-Item "/dbus" -Force -Recurse;                                                                               \
    Remove-Item "/someip-runtime" -Force -Recurse;                                                                     \
    Remove-Item "/vsomeip" -Force -Recurse;
ENV CAPICPP_CORE_RUNTIME_DIR="/usr/local/capicpp/core-runtime"
ENV CAPICPP_DBUS_DIR="/usr/local/capicpp/dbus-patched"
ENV CAPICPP_DBUS_RUNTIME_DIR="/usr/local/capicpp/dbus-runtime"
ENV CAPICPP_VSOMEIP_DIR="/usr/local/capicpp/vsomeip"
ENV CAPICPP_SOMEIP_RUNTIME_DIR="/usr/local/capicpp/someip-runtime"
