# Staging workflow
#
# This workflow triggers whenever a pull request is open, reopened or there are new commits on it.

on: pull_request

permissions:
  contents: read
  pull-requests: write

name: (Staging) - Full
run-name: "#${{ github.run_number }}: ${{ github.event.pull_request.title }}"
jobs:
  full-staging:
    uses: dmg0345/commonapi_cpp_examples/.github/workflows/reusable-full.yml@master
    secrets:
      netlify_pat: ${{ secrets.NETLIFY_PAT }}
      netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
    with:
      docker_base_image: dmg00345/commonapi_cpp_examples:latest
      deploy: staging
      deploy_alias: staging-${{ github.run_number }}
