# Development workflow
#
# This workflow triggers whenever there is a push on the 'develop' branch.
# The 'develop' branch should be configured to restrict direct commits.

on: 
  push: 
    branches: develop

name: (Development) - Full
run-name: "#${{ github.run_number }}: ${{ github.event.head_commit.message }}"
jobs:
  full-development:
    uses: dmg0345/commonapi_cpp_examples/.github/workflows/reusable-full.yml@master
    secrets:
      netlify_pat: ${{ secrets.NETLIFY_PAT }}
      netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
    with:
      docker_base_image: dmg00345/commonapi_cpp_examples:latest
      deploy: development
      deploy_alias: development
